theme: jekyll-theme-cayman
title: Tian's homepage
description: pick up & put down
url: "https://yantianqiang.github.io/"
markdown: kramdown


plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - COPYING
  - vendor
sass:
  style: compressed
future: true
permalink: /:year/:month/:day/:title
